# -*- coding: utf-8 -*-
"""entrega02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14lKgD23H4ussSDc0shpwgTW0k7xvef0S
"""

import pandas as pd

datos_incidentes=pd.read_csv("incidentes.csv") #Cargar dataframe

"""# Eliminar columnas

"""

df = pd.read_csv('incidentes.csv')

df = df.drop(['Quarter', 'Location_Type'], axis=1)
df.to_csv('incidentes_limpio.csv', index=False)
print(df.head())

"""# Scripts de juego de datos

"""

conteo_estados = datos_incidentes['State'].value_counts() #datos_incidentes['State'] es para acceder a la columna deseada
print(conteo_estados)

conteo_por_estado_y_año = datos_incidentes.groupby(['State', 'Year']).size().reset_index(name='Count')
df_conteo = pd.DataFrame(conteo_por_estado_y_año)
print(df_conteo)

data = pd.read_csv('incidentes.csv')

casos_con_victimas = (data['Number_Victims'] > 0).sum()
print("Cantidad de casos con al menos una víctima:", casos_con_victimas)

df = pd.read_csv('incidentes.csv')
total_victimas = df['Victims_Killed'].sum()

print("El total de víctimas fatales en los incidentes es:", total_victimas)