# -*- coding: utf-8 -*-
"""encargo04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tgnvgmngr65L2ADoEktYSvqXkQ9Cs8h
"""

!pip install seaborn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar los datos desde el archivo CSV
datos = pd.read_csv('/content/incidents-new.csv')

# Mostrar las primeras 5 filas del DataFrame
datos.head()

# Crear un gráfico de conteo por nivel escolar
plt.figure(figsize=(10, 6))
sns.countplot(x='School_Level', data=datos)
plt.title('Número de Incidentes por Nivel Escolar')
plt.xlabel('Nivel Escolar')
plt.ylabel('Número de Incidentes')
plt.xticks(rotation=45)
plt.show()

# Crear y guardar el gráfico de barras agrupadas para 'State' y 'School_Level'
plt.figure(figsize=(20, 10))
sns.countplot(data=datos, x='State', hue='School_Level')
plt.title('Relación entre Estado y Nivel Escolar')
plt.xlabel('Estado')
plt.ylabel('Número de Incidentes')
plt.xticks(rotation=90)
plt.legend(title='Nivel Escolar')
plt.savefig('/content/relacion_estado_nivel_escolar.png')
plt.show()

# Crear una tabla de contingencia entre 'Location' y 'Location_Type'
tabla_contingencia = pd.crosstab(datos['Location'], datos['Location_Type'])

# Crear un mapa de calor utilizando la tabla de contingencia
plt.figure(figsize=(14, 8))
sns.heatmap(tabla_contingencia, annot=True, fmt='d', cmap='YlGnBu')

# Añadir título y etiquetas
plt.title('Mapa de Calor de la Relación entre Location y Location_Type')
plt.xlabel('Location_Type')
plt.ylabel('Location')

# Mostrar el mapa de calor
plt.show()

# Guardar el mapa de calor como archivo PNG
plt.figure(figsize=(14, 8))
sns.heatmap(tabla_contingencia, annot=True, fmt='d', cmap='YlGnBu')
plt.title('Mapa de Calor de la Relación entre Location y Location_Type')
plt.xlabel('Location_Type')
plt.ylabel('Location')
plt.savefig('/content/heatmap_location_vs_location_type.png')

# Guardar el gráfico de conteo por nivel escolar
plt.figure(figsize=(10, 6))
sns.countplot(x='School_Level', data=datos)
plt.title('Número de Incidentes por Nivel Escolar')
plt.xlabel('Nivel Escolar')
plt.ylabel('Número de Incidentes')
plt.xticks(rotation=45)
plt.savefig('/content/numero_incidentes_nivel_escolar.png')
plt.show()